name: linter

on: push

jobs:
  super-lint:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}
        
      - name: run linter
        uses: github/super-linter@v3
        env: 
          FILTER_REGEX_EXCLUDE: node_modules/*
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
