name: runTest

on: push

jobs:
  RunTest:
    name: Run Nav Bar Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}

      - name: Install Cypress and Verify
        run: 
          npm ci
          $(npm bin)/cypress verify
          
      - name: Cypress run
        run: |   
          --spec cypress/integration/navBarTest.js --browser chrome --headless
        
