name: runTest

on: push

jobs:
  RunTest:
    name: Run Nav Bar Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cypress
              run: npm install

            - name: Run tests in QA
              run: |   
                  npx cypress run --spec cypress/integration/navBarTest.js --browser chrome --headless --env allure=true,configFile=qa
              continue-on-error: true
