name: runTest

on: push

jobs:
  RunTest:
    name: Run Nav Bar Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}
      
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
