name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}
      
      - name: Install Cypress
        run: |
          pwd
          ls
          npm install
          pwd
          ls

      - name: run tests
        run: |
          npx cypress run --spec cypress/integration/navBarTest.js --browser chrome --headless
